config/routes.rb
Rails.application.routes.draw do
  root 'senhas#index'
  get 'gerar_prioridade', to: 'senhas_prioridade#gerar_prioridade'
  get 'gerar_normal', to: 'senhas_consulta_normal#gerar_normal'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/senha.rb
class Senha < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/senha_consulta_normal_controller.rb
class SenhaConsultaNormalController < ApplicationController
    def gerar_normal
        @ultima_normal = Senha.where("numero LIKE ?", "N%").last
        numero = @ultima_normal ? @ultima_normal.numero.next : 'N001'
        Senha.create(numero: numero)
        redirect_to root_path, notice: "Senha normal gerada: #{numero}"
      end
end

app/controllers/senha_controller.rb
class SenhaController < ApplicationController
end

app/controllers/senha_prioridade_controller.rb
class SenhaPrioridadeController < ApplicationController
    def gerar_prioridade
        @ultima_prioridade = Senha.where("numero LIKE ?", "P%").last
        numero = @ultima_prioridade ? @ultima_prioridade.numero.next : 'P001'
        Senha.create(numero: numero)
        redirect_to root_path, notice: "Senha prioritária gerada: #{numero}"
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/senha_consulta_normal_helper.rb
module SenhaConsultaNormalHelper
end

app/helpers/senha_helper.rb
module SenhaHelper
end

app/helpers/senha_prioridade_helper.rb
module SenhaPrioridadeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <title>SistemaAtendimento</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/senha/index.html.erb
<div class="container">
  <h1>Gerador de Senhas</h1>
  <a class="btn btn-primary" href="<%= priority_senhas_path %>">Prioridade</a>
  <a class="btn btn-secondary" href="<%= normal_senhas_path %>">Consulta Normal</a>
</div>